// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPo4jj2gtR5gaGY2t5WFAHNXvdu1ak-8',
    appId: '1:986744449921:web:1095c7b8dcff740c8ad680',
    messagingSenderId: '986744449921',
    projectId: 'citizen-107-a2440',
    authDomain: 'citizen-107-a2440.firebaseapp.com',
    storageBucket: 'citizen-107-a2440.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt6YhyKVzH6_45S9JJTSdPPJfNSuBP0Mw',
    appId: '1:986744449921:android:2520fae32eaa64fa8ad680',
    messagingSenderId: '986744449921',
    projectId: 'citizen-107-a2440',
    storageBucket: 'citizen-107-a2440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67y6gAmtMIKyUnXeprAllUdi1yRp0NWU',
    appId: '1:986744449921:ios:e0ec29ecc90a86c18ad680',
    messagingSenderId: '986744449921',
    projectId: 'citizen-107-a2440',
    storageBucket: 'citizen-107-a2440.firebasestorage.app',
    iosBundleId: 'com.example.citizen107',
  );
}
